apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-02-29T11:47:44.906448-05:00
    description: Helm chart for Open Cluster Management application UI
    digest: 1f95c5679ab23bae3ccc671a40b91f111a76203446849e6c3d95a91db3df315f
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    tillerVersion: '>=2.9.1'
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-02-29T11:47:44.909477-05:00
    description: Service for issuing and managing certificates.
    digest: e9a5389777e3ac2d6e4557dac45368468ce56cb4c80c8ac2459d38eee74a0cd3
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-02-29T11:47:44.912142-05:00
    description: A Helm chart for deploying the cert-manager webhook component
    digest: b91c7e2e2586c9175157acb263d44cb1e0e18ccf532423a09ca24f4b0ec633ce
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: 2020-02-29T11:47:44.912784-05:00
    description: A helm chart for deploying the config map watcher component.
    digest: fc320f9b7ffbe9f917b641d2ef06ef34b8a50bb46578ab79b00498378224d877
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-02-29T11:47:44.913128-05:00
    description: Helm chart for Open Cluster Management console UI
    digest: 4f6d05b406417c63744e86716972ab07e02df84df50d150db47cd8359dab2e46
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    tillerVersion: '>=2.9.1'
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-02-29T11:47:44.913492-05:00
    description: helm chart for multicloud grc
    digest: 152f73c547209437d1746e4568b9236ba0431b6325c5c560957d53002d2b36a8
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-02-29T11:47:44.914086-05:00
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 0a5d52fbc9f925592d0dd3a9a11a1e1293d8a8a6daeb524b31630e2731e1e553
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - appVersion: 3.4.0
    created: 2020-02-29T11:47:44.914756-05:00
    description: Multi Cloud control plane ingress controller
    digest: 9f9522fd170e35e9fc10ac4690948a683f0b2a3ba6085ab6200ac32eedeff59d
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-02-29T11:47:44.915206-05:00
    description: A helm chart for deploying the cluster lifecycle
    digest: c02a7a8a0fdec8f0e6b6fe1df49f069aa0f82d459394fbfa957cf68edf9cddee
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - appVersion: 3.4.0
    created: 2020-02-29T11:47:44.91595-05:00
    description: Helm chart to install the Multicloud Search service
    digest: d7088ad2a823697ca9ceb08f34f09d70d501b53da4bcb4e8a343d4a6a51da978
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    tillerVersion: '>=2.9.0'
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-02-29T11:47:44.916287-05:00
    description: helm chart for multicloud topology
    digest: 2de8b2fc2bc02b3c7c418f6bca5e81e16b0c9bc2bb65b4b925bd64d3625a4b18
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: 2020-02-29T11:47:44.905895-05:00
