apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-02T09:59:19.597475-05:00
    description: Helm chart for Open Cluster Management application UI
    digest: 3332e388cd470964daf64efa1e3e5879191c29e4ed5cbd92cb282598246c2721
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    tillerVersion: '>=2.9.1'
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-03-02T09:59:19.602913-05:00
    description: Service for issuing and managing certificates.
    digest: e6ceb89bf88dfebc2a6a6bf4ee4fd3333f9f61d2b8c34d752f13717186189750
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-03-02T09:59:19.604829-05:00
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 92be889cdd70e6c2183913161cc834d83324036a5c7e71a52c7398633b2c832b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: 2020-03-02T09:59:19.605355-05:00
    description: A helm chart for deploying the config map watcher component.
    digest: c1ca2649ffc8ddc127c25d538ead01f718976c7e928bab6ab9a29373d2fe797a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-02T09:59:19.605635-05:00
    description: Helm chart for Open Cluster Management console UI
    digest: ecb00e270ae08585f7e501d6f343b86de4c8c186c1f0905234235e2c39686c5a
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    tillerVersion: '>=2.9.1'
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-02T09:59:19.606034-05:00
    description: helm chart for multicloud grc
    digest: 11fe21d3c93239d68debb568e2c640dd086df4e48a9190a2c0f971c24df96455
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-03-02T09:59:19.606799-05:00
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: cf0736c73b9c0e53a92daceae6171e8b12314bece808c8d6d8a73ae650d4ccc8
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - appVersion: 3.4.0
    created: 2020-03-02T09:59:19.608259-05:00
    description: Multi Cloud control plane ingress controller
    digest: 53759261177f9e6d4d95a25b6455efcfda8bcad65c4ff8b473bbd7bcd74aebac
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-03-02T09:59:19.608653-05:00
    description: A helm chart for deploying the cluster lifecycle
    digest: 5ec94435f53e301724147c35d3d52d1fbb19c1923aeee9f4415894e8e3bcc4b0
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - appVersion: 3.4.0
    created: 2020-03-02T09:59:19.60944-05:00
    description: Helm chart to install the Multicloud Search service
    digest: 168da249320549a1b188624a74505047a5f5f1fb29f922ee35af5e0411af4904
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    tillerVersion: '>=2.9.0'
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-02T09:59:19.609763-05:00
    description: helm chart for multicloud topology
    digest: 487bb26796ec419e79f9070fecd5bdf893ec9a0625f9da2c5830a83ded14406b
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: 2020-03-02T09:59:19.595369-05:00
