apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-02T13:02:22.688804-05:00"
    description: Helm chart for Open Cluster Management application UI
    digest: f1dd85096065bf83555d376493cc4d4f7d5cd8930d1c1d0b1d36a66944791f55
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-02T13:02:22.695748-05:00"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 5304d0d83b3d096e6602ff13e69c4abb35e4a47b5d3211019a2471003a27e039
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-02T13:02:22.697397-05:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 6a5ea44f2f61bf7941d43da78dc90ffa64e1a58e81c3fbd46508c6f5def5c840
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-02T13:02:22.698461-05:00"
    description: A helm chart for deploying the config map watcher component.
    digest: bb942718eb45e63f55673e5fd8eabb629f52ff3508f52decd715cb7c2a0aa99c
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-02T13:02:22.699144-05:00"
    description: Helm chart for Open Cluster Management console UI
    digest: bb07f38e12f0fb636797ce4bf8474f969ae00bf5c2845349a7cfe7a29949594d
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-02T13:02:22.700146-05:00"
    description: helm chart for multicloud grc
    digest: b870be62b156255f743d1b817c56085253852b06bf8de1cb057f4dec8f5c69f8
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-02T13:02:22.701519-05:00"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: d6d5be3395706b3a0cef441b3e6d7cfaad1d18b41aa53dc5b6ed1bca15f89e3f
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-02T13:02:22.702798-05:00"
    description: Multi Cloud control plane ingress controller
    digest: 54e54f58087e73b3a3704c478e9d7817434d7e2765b41d2d67bb0b5485a34e1f
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-02T13:02:22.705316-05:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: 4cc3d705024ee83e19354af67d84e87036d653287a7870a3fb47c8e1effc4d43
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-02T13:02:22.707104-05:00"
    description: Helm chart to install the Multicloud Search service
    digest: b3b947e9b0dffc2420f4e9a6a54871f7f4bef009c758a4b11f9f7f1fd041da9c
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-02T13:02:22.707994-05:00"
    description: helm chart for multicloud topology
    digest: 135845f5c700230ee32d92c5a2a8ac63e12caf654aa1999db4a8a0defbe0bf78
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-02T13:02:22.687839-05:00"
