apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T06:36:12.364922-05:00"
    description: Helm chart for Open Cluster Management application UI
    digest: b1044026bc7a067f6ae909bb767e53420e783bbbfa9ae5be2ae579cb6b175f97
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-03T06:36:12.370285-05:00"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 3a075670e3040b8dc9d55271df35939eb9b7336719ff85991728197a64b9f92f
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-03T06:36:12.371928-05:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 2ae7dafe517cce73fb59b87a4ab7691c988d1a7cacecee2777daf9e0b7facc9c
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-03T06:36:12.373134-05:00"
    description: A helm chart for deploying the config map watcher component.
    digest: fcab8b70f244e30289cfb6746bef5deb4b2083c1f0284fe278281efd9d0511d7
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T06:36:12.373826-05:00"
    description: Helm chart for Open Cluster Management console UI
    digest: 3469be5eef2bf9ef4b6201ed77c4f41a11ffacd565fbd65b5a5e035580e1a063
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T06:36:12.37462-05:00"
    description: helm chart for multicloud grc
    digest: 9f2ef248227496a8f044f7751be39fd457e272aec93207c19637ebaa2de7160b
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-03T06:36:12.375663-05:00"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 4850c3e60bd33907dd4d37e6ee524b51fd0cc490152a0d6baf86ad54ee97250a
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-03T06:36:12.376838-05:00"
    description: Multi Cloud control plane ingress controller
    digest: cb786d472f41d275281fe568180b0ebc1a3d053eb5f06940975ab635c12c7a69
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-03T06:36:12.377629-05:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: af79107dbfe1b993deb82069cf59c25a2d51af9474be3f48139ee141ba7a5e40
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-03T06:36:12.378878-05:00"
    description: Helm chart to install the Multicloud Search service
    digest: 62da856da2b0736cae817216f3a129af02cfd209e0a8051d72730e74e7635956
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T06:36:12.379497-05:00"
    description: helm chart for multicloud topology
    digest: 22a545478856fc5a01a946b352c6613e1894d195117ec03dd3027920dee9cee5
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-03T06:36:12.364126-05:00"
