apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-18T20:10:28.311443008Z"
    description: Helm chart for Open Cluster Management application UI
    digest: ca70ae2466efc2c041ca18bc083ed116bb33fc90f406fb5e864a3d55c1b8a021
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-18T20:10:28.312479346Z"
    description: Service for issuing and managing certificates.
    digest: 9ec9fa9cd194444992b78ff19699079b39e13124161fe8a2d9aa7a1864b3fc83
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-18T20:10:28.313705587Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: f902af24cc228a31d0a4f63fc6159e1001323a399687bf0ee2fe246f4a944ea9
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-18T20:10:28.31442198Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 542fc13a4bd7b8765bb98058969ffa902d8eb54e0c1e1871668d1ed2494fda91
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-18T20:10:28.315017396Z"
    description: Helm chart for Open Cluster Management Console
    digest: 428126897ffb58d8cb923b6d84dad88d5f014a872b87f37ff3f51453d419276a
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-18T20:10:28.315385507Z"
    description: helm chart for multicloud grc
    digest: d26506a54bc1cf2060d41de7ede32ea9404fc174f0d94b484d3dea433ef3b6d0
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-18T20:10:28.316200612Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 9c2711328f42d60cc9c8b28a441ffd677a85168098a0f5d8ee5df661b19ba0f7
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-18T20:10:28.317169951Z"
    description: Multi Cloud control plane ingress controller
    digest: c277114a59aa83052591119623a4c77918791ff3af14db88339528f4953a8650
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-18T20:10:28.318616765Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 811e5e662ae990a95d78d5283e7ab2973aaa94c07865e39c783ced8676795877
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-18T20:10:28.32079184Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 15502d14aa9cad5da509f3056caa1b100f145a0c56a1d3b56b65414bd9739d4d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-18T20:10:28.321744618Z"
    description: helm chart for multicloud topology
    digest: f62b75e510745b24647cc1a74d9c05e571da4a7cb13d52980dc7f4be1103869d
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-18T20:10:28.310869813Z"
