apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-12-18T15:48:32.667507398Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 30752bd76deaf24f013008a96ef82be8ad23c9baabc0db9528190b08578e4082
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-18T15:48:32.670689044Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: a6750f091ca51457968f858c0148aebdfb46caad0a6ffa19b1eda8bbd965feb5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-18T15:48:32.672069221Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: c9aabfeb4861ca6ed593df222aade3177d428dece417e1763d7f586fc0e24f27
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-12-18T15:48:32.673222871Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 0931485b73d91a84237481d30c243ed5b57c14e1d73a715f6ff5dc4ad78358af
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-12-18T15:48:32.675285625Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 5d6c3fbb234b2966e3a24b0c19f80fb2b51c327d7d688a14bb1bc255bbcf9183
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-18T15:48:32.676356287Z"
    description: helm chart for multicloud grc
    digest: e3e84be568756171299e38f9d8a73107a003de2967fba343ba81097021813b11
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-12-18T15:48:32.677700809Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: ab7911c4508a79dff34a0475166849cd88666e3fda825c3ab8211363001f509c
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-12-18T15:48:32.678662103Z"
    description: Multi Cloud control plane ingress controller
    digest: 5d4a917125a260f7377fb9a62b94c44be40db8c8e712616812998e43ae804fe5
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-12-18T15:48:32.679519635Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 5cab5f8fad8ea5178a5bafdc0df3f41fe966cf6cd98d860f9ec1dee2c5dedc13
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-12-18T15:48:32.680554619Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 6ec86a4ee7699754d3a6295d4aa923ef13f3dcef0942590085c656b254c7cc34
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-18T15:48:32.680963826Z"
    description: helm chart for multicloud topology
    digest: 173f641f3c1b9e6bf59514fc605d386ebc0f50607915a217fe7c9ce0bad0763c
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2020-12-18T15:48:32.666888681Z"
