apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-03T21:01:23.572288211Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 8f76c12e4316ad36fb2e792f96267092a615807f4cafcc2c2f592342f7b263cb
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-03T21:01:23.573406744Z"
    description: Service for issuing and managing certificates.
    digest: 196103f883160043f0b9625a7899ac3cf7a50c4677240c8bf50a7c5f1ba92af8
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-03T21:01:23.574736251Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 6ba1a91735512d96e1d71a34c844acb0edd1d9401393f8969a3101fa990c2d96
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-03T21:01:23.575430983Z"
    description: A helm chart for deploying the config map watcher component.
    digest: dc76e9476b8c7d29ded920a420d56caf7e3b0a20dbd8947edcb1e1534d8dceb3
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-03T21:01:23.576092816Z"
    description: Helm chart for Open Cluster Management Console
    digest: deec94650c0225a4289c49c1689071aae96ef7e2ec29549d58c7328fedbb5a1d
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-03T21:01:23.576504712Z"
    description: helm chart for multicloud grc
    digest: bfb1ab00334b9206e15c1e24093c683adb821770dbbc73a30255bd671092fc93
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-03T21:01:23.577358748Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 4f0021eb55eacef3a6cc953b10362b80485e55dd5691a519637c35953d114ec6
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-03T21:01:23.578374202Z"
    description: Multi Cloud control plane ingress controller
    digest: 8eaa803d3ef18edb2cab0cf50a2049f884943f6557c1eabfae135a3a8ada3b8b
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-03T21:01:23.579331628Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 061dcac619322912d59e1f8dd283a2085523399ab70ebe24cf63d4bd144e29d0
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-03T21:01:23.582647614Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 8ed95349915e726133ed9db2e845a8e76c64167159f39222539433dd5e67da35
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-03T21:01:23.583799118Z"
    description: helm chart for multicloud topology
    digest: a49b5cff53a337a75d28b96fb4534f7d94b374884edf79807135ebfe3911c7a7
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-02-03T21:01:23.571574645Z"
