apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-12-16T21:50:08.97418534Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 4af471ec4071c39fe4204c702bdf4fd3d06a9ccdc6e2cad274818c2b8ac61971
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-16T21:50:08.97798617Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 739986fe1f4dd36017d1000b59842fc0107729b06e19c8bafaf6661d9dfc9c5a
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-16T21:50:08.981084705Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 0a201ce9a068d1568a094d11ca5ab7f3fb5ef20e2e543bdf6369154182dda2d9
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-12-16T21:50:08.981843162Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 7a3c000d643f9f9378ce2a78a8d9747ec250a64da8ce6f8260f26f46b28133ab
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-12-16T21:50:08.98272173Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: d78065d98373fdc0ced0b95dce60d9b96460654034fe6dbc07a80162c63dc623
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-16T21:50:08.983250892Z"
    description: helm chart for multicloud grc
    digest: dc81601f8a3f8450210b156740e36b35d6ca770ac51c5c943c68bafb361e112b
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-12-16T21:50:08.984044349Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: d02c9ff5377b46933423d36f31f3b8fb4dcba2b9be176447acbc51154d9a464d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-12-16T21:50:08.985004299Z"
    description: Multi Cloud control plane ingress controller
    digest: 87da8674ce3bcfd16f9d393db126a0466f7b97bf281f1226866fff9ab8fc6e9a
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-12-16T21:50:08.985812335Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 83d677be2d4cf6567f4f9e66fd6243b5e818e53ffc3d74dffa348a4fe5122458
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-12-16T21:50:08.986867623Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 5d14dae45eecbe4924216f3a3f4e77f36105170d65c37bbee80cf45af924bf41
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-16T21:50:08.987297164Z"
    description: helm chart for multicloud topology
    digest: ae3d4e3ec5be65b8b84d4c42e140f16bad7a4056e4e010aa93badd919250bf29
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2020-12-16T21:50:08.973585433Z"
