apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-22T21:09:20.079224249Z"
    description: Helm chart for Open Cluster Management application UI
    digest: a512de194754bfbae0db3f0d4ff91fb6eed4b5f72868947f10de048a7e261951
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-22T21:09:20.080277247Z"
    description: Service for issuing and managing certificates.
    digest: 5c1006a062544bf52430b2e6b9768f0f5285149fdf2e0faeecd33a5066f9b075
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-22T21:09:20.081682181Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 7f528c24b08d6ab4ed33e371b6506f116cd8f47c741fad88490bea7f4f22ad35
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-22T21:09:20.082339087Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 07d5bc516979f1b71853def6047fec65cd7629760aabf625f980faa02db817fd
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-22T21:09:20.083011752Z"
    description: Helm chart for Open Cluster Management Console
    digest: 1c49d2fa301a59cddb7dd952e51b30354fdefdba76b60dbac28831ba5c6a254d
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-22T21:09:20.083434219Z"
    description: helm chart for multicloud grc
    digest: 0347abc6b155c50c7674aab7580ee2092936ba774023bd80015489637937fba6
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-22T21:09:20.084259529Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: db6f8dfd5d211506c096c38c8a187d30f0c2209d775c502915c2389420a198a4
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-22T21:09:20.085249217Z"
    description: Multi Cloud control plane ingress controller
    digest: eab50fbab8847ebc50a577efe6aa12d710209e83fa07b3e8f0ca773570d23f64
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-22T21:09:20.08612326Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: d1595f11a206fbc727285a6b850b0a66d3762e9be6d81ddc5187454c206e8456
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-22T21:09:20.08748109Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: df42f06733a07bcd84e52207bb5ee30b05c3f3f27984e1a90c178732b551364e
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-02-22T21:09:20.078554922Z"
