apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-23T20:07:47.803816854Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 0dfe038c9b34d20b2d42eb83ec45563e3257235a164207b6fa262500e05cb4ec
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-23T20:07:47.804831203Z"
    description: Service for issuing and managing certificates.
    digest: 427bf86e31d687f8f6854289039c3272ed58d3b3b3b754cfa8696885e3fdbd1f
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-23T20:07:47.806200369Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 5d115285615856954f47d7dedb5cf28ff65d07f95e0b33014abcca5350d90e82
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-23T20:07:47.806849293Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 83a58bb932b8e7421599fcf0a4ae0d84c0c315ec73b527ddd65744ea085afa2a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-23T20:07:47.807536709Z"
    description: Helm chart for Open Cluster Management Console
    digest: c11ae695c92ba0f8be7a60ad54faa730bc0e6117d0d3d379a505b9daaea335ff
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-23T20:07:47.807984628Z"
    description: helm chart for multicloud grc
    digest: 0621dca2f6cb88dfe090de4abf42c08d55a403573fc03852e6a32a47a51d96ed
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-23T20:07:47.808881253Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: b740f7b302a01145b431dd4545fac9172b77c8255a3fbe909e50acb26c3d5663
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-23T20:07:47.810871399Z"
    description: Multi Cloud control plane ingress controller
    digest: 5fb728096e2af4160ff09a13ca43d0f02a2a198e2218040dba7010ebd9f7dcec
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-23T20:07:47.812775989Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: a7084f5c499bd419c131c5a38ae8175af93a59642406ac14793c287e3f7420c6
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-23T20:07:47.814622808Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 4a37383182348f5a87a606ea773f2ee5af9e36fd5a1010239d8f3b895da71858
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-02-23T20:07:47.803192181Z"
