apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-12-01T21:33:44.012681866Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5e6bb85fbef3714d3bc0d1bb03a1c56ccd66257a30768be9828acf2edaa87588
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-01T21:33:44.015956349Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 37e7bd02369d671bce6c62c6c0c10a93fc4cdacd50dad3e7392bfba9b5a07717
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-01T21:33:44.017382559Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 959381473ae0972d5c9ee90675f5820fa4121c535749c3fb57c6b28121435efc
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-12-01T21:33:44.019407882Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 7f8f37e0f06a3969a17be20efe3709ff7df8e084efa6dbe9b618aa9abc78d21a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-12-01T21:33:44.02169966Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 9d8783a36524d0bd9dbfb6212497531f95feb7df912f0330759e004ef051a189
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-01T21:33:44.022285927Z"
    description: helm chart for multicloud grc
    digest: abfaeded09b3db483832cf554b54fdfaec87778eb762b29de2a8c9516e0beb05
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-12-01T21:33:44.023059932Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 7eb5b100a97a1294f65c71804a43fac9f758fcf3e77f4c4dbaa37138caec1610
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-12-01T21:33:44.024004013Z"
    description: Multi Cloud control plane ingress controller
    digest: 7f31d86baeacb1f220b7bbb1f5b46f46fb8402a259b9d3a90e1392aaf3aa9ff6
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-12-01T21:33:44.024925598Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 97e669b7a27c26079704da64d41813e00b78fd8d88888a9f668b74392612d9b9
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-12-01T21:33:44.025918577Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 7eee63e06f86b44cba5ffac29566b196f91db6ba1a29e7fd48eb1fc463425195
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-01T21:33:44.026329655Z"
    description: helm chart for multicloud topology
    digest: 80444332096e9ebe1e468f5aefffde5c5288ef88664e0ca670f160181411ac93
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2020-12-01T21:33:44.011956904Z"
