apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-09T00:08:00.451209856Z"
    description: Helm chart for Open Cluster Management application UI
    digest: a18b67ad649f46a056527d23dcaaa5357b822f23fd0e5ab7a96933fe6c909244
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-09T00:08:00.45540984Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 40cf6b8012d5fdce700758c1520eff0efcc1c1d6f2536c03753e68535fd8416f
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-09T00:08:00.456761974Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 1ff08924cd1970afd95575ec5689c421a8967d8551e33613ff58dbcdca2b88be
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-09T00:08:00.457479735Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 7dfb28bae1cec42b7cc8c1ba2aa31cb9aa1f813319023b5cdfcf5c0b3787f081
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-09T00:08:00.458308778Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management Console
    digest: cdb8b35cbaa7207abbcb9d2d8f3d65b9afe3a7dcb266df3ac94af9b4452817ba
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-09T00:08:00.458779292Z"
    description: helm chart for multicloud grc
    digest: 559a711fcef9d3ca66e7ec068122bc82bbf6108c80a279ad0487376714de287b
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-09T00:08:00.459690626Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 464732971c4edf49b62ec8e1de2fdc5abb7810649007c3c917daf37e9c105524
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-09T00:08:00.462195971Z"
    description: Multi Cloud control plane ingress controller
    digest: b00a034748480b0a645a359345f53381649369a8b0ec108c1413db5460e75b13
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-09T00:08:00.4641481Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: d0a238e7ac8649ebe44adf2d592c3ab6e0f3a5aea19e63de047c202318d3ede2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-09T00:08:00.465245505Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 8fb61f2524e85282fba579be2d26f055198b8cd19741d262436d75dc8c196b3e
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-09T00:08:00.465670566Z"
    description: helm chart for multicloud topology
    digest: 88fec88c6baf1ea4ee7c96ca203e838271ecd398c2f5a158c6f70967b88c0c9f
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-09T00:08:00.449310479Z"
