apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-25T16:28:11.760384357Z"
    description: Helm chart for Open Cluster Management application UI
    digest: eba11439f47a9319619c07c3c30c79d9746719ae87a6b8e62e8b235a8bd532f6
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-25T16:28:11.761435044Z"
    description: Service for issuing and managing certificates.
    digest: 5751bfe58dbea3bc9977ac6307b47435e9eedf774935d326930af8c0cc924e1b
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-25T16:28:11.762856502Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 17e3a3e2cc68ec2df80977f1178ae7923fd665d997a5b3c2d199ff85e23a6666
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-25T16:28:11.763531318Z"
    description: A helm chart for deploying the config map watcher component.
    digest: cc39db4b0feacc78c546e0778c0477cec5f960efda965f8984b11d94faa4a89b
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-25T16:28:11.764224405Z"
    description: Helm chart for Open Cluster Management Console
    digest: 5e5b192e9ffa5da2139c0990fbd68b3ffaad18b2d66b3eaa9cc6d948e23b9432
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-25T16:28:11.764661185Z"
    description: helm chart for multicloud grc
    digest: 0369e373d2c8f46ef2731672380769a8cbfc8d321e1eb72ac07fdad8d4c71963
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-25T16:28:11.765518563Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 90df502f976fbfd97a03ed3aa96846c2d52ba020209685b9bd52263488d9e8b8
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-25T16:28:11.766517935Z"
    description: Multi Cloud control plane ingress controller
    digest: b49083cc429f5027852d15b542e466c14cd6fb673515b480fd7b164bd25f4c29
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-25T16:28:11.767406633Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 239b34a7d9b121bc996118e1404689d40cf79f3db0081814e40d9d51775f7e43
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-25T16:28:11.769713367Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: e159511c0e1486ffdde1801ca07fb20a4a3140caebcedc7ecf9afd539fbb8f17
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-02-25T16:28:11.759732871Z"
