apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-03T20:00:48.331872768Z"
    description: Helm chart for Open Cluster Management application UI
    digest: b3f5b9f067dcb41d9539685cf93e3d8a15ac24bbd6bb2898a1b6467a511497e9
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-03T20:00:48.332872432Z"
    description: Service for issuing and managing certificates.
    digest: 18d7fcc14807df30d3de7239c5c5980cb953b5ac11e1f630d634859457450071
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-03T20:00:48.334121692Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: ca0e3cd7ace724f927d2d3d2d49e21b6a2eb652d12cbdc497b35639315d43307
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-03T20:00:48.334771313Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 9ab591938ae5806937e6cf95fd2dc4255fcf07a41acd01ee3df8bc938349fb94
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-03T20:00:48.335422582Z"
    description: Helm chart for Open Cluster Management Console
    digest: 8984642835b63a6fc300f973dd18cf040bc045de12f88bebd66039dbf5853ade
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-03T20:00:48.335814133Z"
    description: helm chart for multicloud grc
    digest: 13db0ff79683c1e8b615b961d775d914f071154935a6acb556bfdb4d56e80fd4
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-03T20:00:48.336611442Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: d8316e07fa621ebcf50d3f68452beab744606778a9804df35c023cd371995e7c
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-03T20:00:48.3375813Z"
    description: Multi Cloud control plane ingress controller
    digest: 14de7456b62f823559c2075e2696f14dd8bb239fee4b7f69d25e727654bdf47c
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-03T20:00:48.33899577Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 49e494751d78cb3ebae280e47663652f7ab92184ba66c69c0f504cdb44a38482
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-03T20:00:48.342058896Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 01a643e67e3abba82ccf4b9ae6da5994e92e8348e3619ea48262dcdb8a3e0e35
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-03T20:00:48.342491103Z"
    description: helm chart for multicloud topology
    digest: e05c76a71f9f397fc172dd96f65394000e716daf5d93b0dda6a6a1f3c042032b
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-02-03T20:00:48.331266849Z"
