apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-17T16:32:12.245232938Z"
    description: Helm chart for Open Cluster Management application UI
    digest: b9d4617968105b5291ca245b86bdb8ce859556f2d875abbc7066391a6e123444
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-17T16:32:12.246298005Z"
    description: Service for issuing and managing certificates.
    digest: 94e1c324efbb7b6241319e768941af6d14f694366e175c8d2be421322bc356a1
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-17T16:32:12.247720778Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 9b0370319e6075334c5ec9993632255359a3e47ce0293086691566e700df884e
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-17T16:32:12.24838382Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 3433a228d2a1f3ac82a8c49333adfcfba5fbc94b6f1a590ce63b0dd5d26e97b0
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-17T16:32:12.249114779Z"
    description: Helm chart for Open Cluster Management Console
    digest: bbc30aad49aabd85feb93929674f7af4f93f38d7f67611d3a202a565d80b65e1
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-17T16:32:12.249593277Z"
    description: helm chart for multicloud grc
    digest: 4822c1acb6d55a9b96879a1775eaee02bcc2e17abb62b280c651dcbdc7663850
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-17T16:32:12.250502369Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: c6ac87be2275cf40277711c80c39984ef839d0d693224e7b042322ed4ef204ca
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-17T16:32:12.252704884Z"
    description: Multi Cloud control plane ingress controller
    digest: 7c4109142f4842ca017b04bfc2c22386a83e19bf73a0511c5cac6339edfaf5e0
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-17T16:32:12.254641782Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 570b2fa0d0babf53261d6594de7c4b13792591e341fb05bea600103de5d8b9fa
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-17T16:32:12.256136803Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 47f75c873032b4d42cd4eda3506972d2830f2a9f94cf4f840ea814fe0943d637
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-02-17T16:32:12.244584057Z"
