apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-11T14:01:31.460674414Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 21a5c1c80d010ace5e7c410e0a619eb0a60881b4a87df1ffae17cdcbaab383cd
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-11T14:01:31.461692309Z"
    description: Service for issuing and managing certificates.
    digest: cd3dfe129c3c7c67d416cd753f64b10a55172b69684c0345da2607e4a8ddf216
    keywords:
    - amd64
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-11T14:01:31.463056145Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 7f6988c32a89cf77b441599be0357a29f2e7082d1f8291339bd109669ea05e9a
    home: https://github.com/open-cluster-management/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/open-cluster-management/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  cluster-lifecycle:
  - apiVersion: v1
    appVersion: "2.3"
    created: "2021-03-11T14:01:31.463903518Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: dbf8365599ff24b3e53ca3667d21f61e7a3e86041ec4ecf879b8e1c4a2eb0e3d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: cluster-lifecycle
    urls:
    - http://multiclusterhub-repo:3000/charts/cluster-lifecycle-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.8.0
    created: "2021-03-11T14:01:31.464587972Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 4f80dfdc604ddb914d50ad2216cb8343e8babf2ba47d563ffe69c85a02f4c35b
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-11T14:01:31.465293552Z"
    description: Helm chart for Open Cluster Management Console
    digest: 475470b5cee4dc8ec3fcf5f0668e88ea99f3afe6f345aded6083e8d764b49a5b
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-11T14:01:31.466639429Z"
    description: helm chart for multicloud grc
    digest: 839ec05bc642d91514ad54e15ea550700c67d1cb5fcf8c7a95ea16c16b408ea2
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-11T14:01:31.468293568Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: e4f064d87a3bd3358eb3fb7e671d1030217c2f203d3fec86e7f4f0d1a58c2a71
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-11T14:01:31.469728629Z"
    description: Multi Cloud control plane ingress controller
    digest: d94c4ad53b96c2f5e1a120de22959417396563d03a535109feea9dc86ae475e5
    keywords:
    - ingress
    - nginx
    - network
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-11T14:01:31.47051461Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: ce2ad230fb22de4dbff5ec1c249ae04612d876117538651f4b19efc7c5b68e3a
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-11T14:01:31.47182721Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: a507936a9a187c5d4afabd94d055cc39637b47e8c41035340d14810e241e3ba0
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-11T14:01:31.460031833Z"
