apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-19T15:14:46.836127807Z"
    description: Helm chart for Open Cluster Management application UI
    digest: d79f71149273f3027dd079886569d68cbf15c69cb2c067374c92c7d5a6673b3c
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-19T15:14:46.837154814Z"
    description: Service for issuing and managing certificates.
    digest: 964fd53eec81d8123d823f074a31546b8ab46f1fa3233bf21b8b3b1c67c96b9a
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-19T15:14:46.838411347Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 8007b70fcf9bf9fbef3cf4ab9b9791426608a415ba3531f9751351280c8058ac
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-19T15:14:46.839027636Z"
    description: A helm chart for deploying the config map watcher component.
    digest: de9a343c033afba820d16dd38b96708ee7b7a79d791690d4ee8a8d59aeccc62c
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-19T15:14:46.839686396Z"
    description: Helm chart for Open Cluster Management Console
    digest: 2ec3c96fe44e8e6a802785ecc1a911abc8d1451e1e9fb65e24c7da90d8f4a8b8
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-19T15:14:46.84010054Z"
    description: helm chart for multicloud grc
    digest: 834f256eef8946279acf1423248533430fe8703bb5fbc2e0602419a3ec28b205
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-19T15:14:46.840954254Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 3e9d170dd7791d937232daba39399e474c78d77abccbd79d2f1b394a434c704a
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-19T15:14:46.84326197Z"
    description: Multi Cloud control plane ingress controller
    digest: c9d22d93e37ec5e46fc389ec38af0f2c0fe88a408b8c31507366660631eb42c0
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-19T15:14:46.844900216Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 0605fd6831371e18a6bb8a87924940db5ccff471d769e4e4282140147a88ef15
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-19T15:14:46.846292029Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: c21685baf10780fd8d3c4b13644e443e20f58e6c29d171e04c745d6bf147e17f
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-19T15:14:46.846691733Z"
    description: helm chart for multicloud topology
    digest: b27220324e0521a9d9bfa74c14bda258eb916bcac8f1ecbabf8ede6639270ce1
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-19T15:14:46.835511244Z"
