apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-02T05:52:26.579978039Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 278e8c9400b5f36b3cbe1942f68d37a785fd9c2a60d75ecd928c48484991bb31
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-02T05:52:26.581125793Z"
    description: Service for issuing and managing certificates.
    digest: 1ea37d45fe9a419dd3c87419cf67ab2378b32ca5e87fbd309ad4399232a9a185
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-02T05:52:26.582497669Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 151fa006e886d04310e2fee853243d614be0be493cedc336ec4ebbec08fe20ac
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-03-02T05:52:26.58315751Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 21e328b26ff6f7951e9aa40812a8550306d4a3ad0713a16cd3241fa7b86a447c
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-02T05:52:26.583826064Z"
    description: Helm chart for Open Cluster Management Console
    digest: 3bfdeeb6373d4d7581c9842f527e97b49bae8200362db1d20525758e35bb3e20
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-02T05:52:26.584293058Z"
    description: helm chart for multicloud grc
    digest: 31d33c70f5c8748845b1b9d271c9c37276ee973946b2656de59e2fdc170c2323
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-02T05:52:26.585170777Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 070b65b515b45e767fe533779c639ea43921413680f52f56577906f9292f3cf7
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-02T05:52:26.586869725Z"
    description: Multi Cloud control plane ingress controller
    digest: 99066832400ba1ccc66327ff3e0f7bd7c3650aa42de939cad16e1ba249e6ddf5
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-02T05:52:26.58873718Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 407f49c4950be5f7514e560093a2451170ba5fe52fce83e3c2065ee4c6427729
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-02T05:52:26.591214085Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: e3d0338773ce8ac7a684861f8db92b06327b863870ae55cd04028a912f238103
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-02T05:52:26.579314364Z"
