apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-18T19:56:10.992060818Z"
    description: Helm chart for Open Cluster Management application UI
    digest: ca49389005eed4cf43d6bfc6066aa440ca668dbc32bcc2c58828aca3447dda62
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-18T19:56:10.993138958Z"
    description: Service for issuing and managing certificates.
    digest: 0162606d78a85933b53a59a1d7c5920023a6086955ad2fb0707fe3611533ffb0
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-18T19:56:10.994510096Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 951a738ce6060cd34f117c861a8c4ff5ac2d8e86ee14a684c82d1d164d20e80c
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-18T19:56:10.995278316Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 2d5f3dce09a4ac6702c2bc0b97c4f846d693bac9a6064222a5b3986418555431
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-18T19:56:10.995924075Z"
    description: Helm chart for Open Cluster Management Console
    digest: 68596e0e6a857fff1db97e5a64cf10ef0318da8e2824d5dff00227c232787ec8
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-18T19:56:10.996388493Z"
    description: helm chart for multicloud grc
    digest: 1fdcc364b6101f87c9b6917c49bbc5813ab840ae0467a119d9a040ae1ebb2533
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-18T19:56:10.997336688Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: a5ed60270f20d5dbfb487ffa0adb1ca751744de99fc01141a31d92334db28cf0
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-18T19:56:10.998421598Z"
    description: Multi Cloud control plane ingress controller
    digest: cb4149a2146c15cf25c0609ca09689faed094dd4b466776493a3c40ae1d206a6
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-18T19:56:10.999297123Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 0c699a1049efcf41d86df6a3837c2c1311489afea3515ba15494cdfa228ae2f2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-18T19:56:11.00171077Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: d365c2f539715b61511d6a3bd7649c6fb436d8aeee5d12d5029066a21f233c9d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-18T19:56:11.00265555Z"
    description: helm chart for multicloud topology
    digest: 4a064d91bfb4170e3b82aef44f9979635e67c5a4bd8c3565d3ff007db8f8d710
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-18T19:56:10.991405733Z"
