apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-08-25T20:14:56.175595443Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 6db638c5442c935e7c04776b865c626044a45734dd7c785c1eab111ccaf041cd
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.0.tgz
    version: 2.1.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-08-25T20:14:56.180160863Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: a32a8fb0092242b408d3be0735eacd3cae93891cccfafe504ba2fe674dfa20fe
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.7.0.tgz
    version: 3.7.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-08-25T20:14:56.18163601Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 749dd52a0cc0ec2a105940c2d3895f99f9157657c09cd37c7524d27a57d5b78b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.7.0.tgz
    version: 3.7.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-08-25T20:14:56.182502535Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 7aae25e97079e058033f70a7bc59b4b37065bf177462ad531f40940df1231222
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.7.0.tgz
    version: 3.7.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-08-25T20:14:56.184709495Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: d79a5be1a07c65d6a16685c15452c97f9a301aee317568ae3eb51c076a90de5c
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T20:14:56.185754033Z"
    description: helm chart for multicloud grc
    digest: 5b7c2cd7a1f6481f43f48c9b9ef25b5d1701e38d4a706905b0dca7aef5645ab0
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.0.tgz
    version: 2.1.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-25T20:14:56.187200375Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 43bea32188d6225981363b355b09535608a890f2b8f966a8707ba38631c6afc3
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.7.0.tgz
    version: 3.7.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-25T20:14:56.188300047Z"
    description: Multi Cloud control plane ingress controller
    digest: d0a7db141e8fbdbdebab443eab17ff58958b33c29cea31c25adec4cf8c22aba8
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-08-25T20:14:56.189209193Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: c06fc93c84fc8a87f3e26fac3b0c7ef059c2207c6073cde3c2dabdd7b37bb9f1
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-08-25T20:14:56.190307192Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 3ec1f1575eb3bb0c2a8ea19284e9d7c46675cd34fe187babe09b00d368cfc2bb
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.0.tgz
    version: 2.1.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T20:14:56.190776966Z"
    description: helm chart for multicloud topology
    digest: 84581e8a2e9b6f95d5033bbacb3f54cf34797db4ee2c582534df380bc4a7bd85
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.0.tgz
    version: 2.1.0
generated: "2020-08-25T20:14:56.173818818Z"
