apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-08T16:01:33.599005204Z"
    description: Helm chart for Open Cluster Management application UI
    digest: e5bd5be08a616d69bd9a86fdb5b4aeed69d2e286d7a33ad3dd61a7ac39a31f2d
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-08T16:01:33.600069317Z"
    description: Service for issuing and managing certificates.
    digest: eae15992175d08d8320658caa8bbd4f132aa291c505b89c67d94e2b402c50c40
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-08T16:01:33.601490944Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: c386a545a80581dc6dd6a6bf58a96cfed8288184366b9209c848fa276c68fdbc
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-08T16:01:33.60220814Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 8a27e9d21eeab648cd1362614fd635b1b95151d07dcc9414ec4ad88f75b70dfe
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-08T16:01:33.602883428Z"
    description: Helm chart for Open Cluster Management Console
    digest: 9de6b102d969d2267471da80fdf52a3bbfe6b97b36a825a5ecc6d023db9069de
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-08T16:01:33.603846285Z"
    description: helm chart for multicloud grc
    digest: ffe203942abbbbf734c75206af1a8858954c039e330284749942d535488c2559
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-08T16:01:33.605549129Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 5390e9af081f0bcf704ab5cd05022352e95b60f0f2ec2d328af32b8d5b678162
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-08T16:01:33.607799589Z"
    description: Multi Cloud control plane ingress controller
    digest: 8a1ac3ec64e11a9e3553b2d6f126c639d1b15a6d668c38576ae1bdd75a57646f
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-08T16:01:33.608676234Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: b9733ea32a516a06f6488a36c04a9c9406be6c30271ff112d49c74618790a3d8
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-08T16:01:33.610008581Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 52c50031d06c2337abedd8c558cd5724f1c1870a26a079d941f7cb4e33578380
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-08T16:01:33.610398335Z"
    description: helm chart for multicloud topology
    digest: ba034b97ba3f127a75d65cf9644254213900ec43e5089ab230bb506ddf3aaf41
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-02-08T16:01:33.598298033Z"
