apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-18T21:08:37.809112449Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5da5daa2fc2cf1b5aec19668ca0a8c308790b4aa35af191933ddd91377492aa9
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-18T21:08:37.810189716Z"
    description: Service for issuing and managing certificates.
    digest: 5b47cccf4d3506fcad3e2ce0eb141b596ae24812f30ea59e73368c57001cf1ac
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-18T21:08:37.811510304Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: ba2477312a36f1456d911f6347b8c3c907e66bd1902c7eaed1330d17a14a1acf
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-18T21:08:37.812230389Z"
    description: A helm chart for deploying the config map watcher component.
    digest: adeb77e172cf5d202c2731eaa611fd4e631b3eb0ff6c6314e6f888c184cd7d04
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-18T21:08:37.812928877Z"
    description: Helm chart for Open Cluster Management Console
    digest: 8a37dc42503393c76d756d2c538cdc930347b551e66bc5eb1d78bf6a1478bf20
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-18T21:08:37.813411509Z"
    description: helm chart for multicloud grc
    digest: 06541d2b872d77299e86c5d7899b38fab8ad1a157dc54b9f085e30eb236376a7
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-18T21:08:37.814302836Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 955311e3a504153642ed50d4685d6a13f35946e049c036a732e54c47cef49882
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-18T21:08:37.815372062Z"
    description: Multi Cloud control plane ingress controller
    digest: 98a3ad4bb49c6ab51e6a9e95bb8cf5b99386e94f1b2879e79371384ecf48817d
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-18T21:08:37.816272861Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 7cf198eaa6724c9684e4d028af8d4ebab026339917591beae3d9101f3e2485fd
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-18T21:08:37.819863911Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: eebc1a1da879ec5af6a06609d0e065d49706fee59b7844b6cf322606729f82d4
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-18T21:08:37.820799104Z"
    description: helm chart for multicloud topology
    digest: 99dcb0034e8e008f5b9e1777fa169e2b05c49214248c5659945221c6a99b8540
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-18T21:08:37.808372805Z"
