apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-12T02:53:11.679060617Z"
    description: Helm chart for Open Cluster Management application UI
    digest: c99de9895677ce131378db7b1ba02215ed6b022d19acdc0b86e70a6d1e12d6f7
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-12T02:53:11.684695176Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 8b837f9f12603f6fdc8b8e74da787ebcfd2d4324a04c9c1f6b7d0f5dfd72784a
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-12T02:53:11.686264852Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: fe392cb9d88c916eb7ef2699ee6ce81d2d2b0a563e7a4152905138eb6a387bc4
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-12T02:53:11.687137963Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 68d13c754a7edb4996ee205a2b0fb7a4111ed2dc681e37be2f5467fda4832f98
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-12T02:53:11.6879823Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management Console
    digest: fba84c0eebdd5687d583ba1eed88301ff16015175af72448d0cfade266ee7f75
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-12T02:53:11.688485334Z"
    description: helm chart for multicloud grc
    digest: af8e391a1a426104b381bc809f6d06872e9381bc64522cb224deedfa35a5bbe9
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-12T02:53:11.689347814Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 39bbc0ce4338a0d038f7094d809acee0a9af6100300fbf2b9d7d9360fa501692
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-12T02:53:11.690469434Z"
    description: Multi Cloud control plane ingress controller
    digest: f63e13f944c73cbc9b118ec1557c31fee89d645383125210ce053137333c3bb1
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-12T02:53:11.69154982Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: d9e171356b20990e93ff1148a07276e9802ed7c72ed8620bf76cb94f9db461f5
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-12T02:53:11.692769035Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 170dc1e0333f0bf61462d998fde669df0c97e39d68b51a629085373bfbe428c0
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-12T02:53:11.693213024Z"
    description: helm chart for multicloud topology
    digest: 1ee8be9a65321f9f474421b9a5195aeb5d53cac8045e8635729f98b2aac6acc8
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-12T02:53:11.678372653Z"
