apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-03T13:26:26.965315318Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 6cfcd85cfe507a66aa7b6e70e303c1b60bf0351edd15a4fa8430260a14797344
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-03T13:26:26.966445715Z"
    description: Service for issuing and managing certificates.
    digest: a51b89d93f1cdd1389cbfe745e559f2ee283ed9abf7f615a2d487877fdd24dac
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-03T13:26:26.969417395Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 2aca28cd6cc6a3a969e77274ff981901241b5b495dd726156569989c2c670af5
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-03-03T13:26:26.9709824Z"
    description: A helm chart for deploying the config map watcher component.
    digest: b03b08a9d2848a7c7c97b5fe9926f9c5666ad6e11d55e47baaefbd673615ffff
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-03T13:26:26.97170438Z"
    description: Helm chart for Open Cluster Management Console
    digest: c4e516ece58a0a8bd13f8f47e449752baaf22520785f2aea8757c438473d992c
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-03T13:26:26.972195315Z"
    description: helm chart for multicloud grc
    digest: 66c47c6333c476d0ebdc9db5e5c2cb318a1dd207e6b69a750fd51a6711449116
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-03T13:26:26.973085694Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: e83eaf3c026d62f06fc305512b52633fbea56aa6a10491e970e765e08d147cd3
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-03T13:26:26.973982977Z"
    description: Multi Cloud control plane ingress controller
    digest: 79c41945859ae7c939403b4216d8dbd5a8c01e6b4e3b35af6efe4e578a1f0f33
    keywords:
    - ingress
    - nginx
    - network
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-03T13:26:26.974794166Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 80a1bd00211aec52e5436df8b62daac4d5c15cf94fcd0c0ee94c161da51b306b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-03T13:26:26.976217034Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: db550104d7af5295b1e11ec062cdaf66c52ae91a9166c5c38f4cd4cc730c36fd
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-03T13:26:26.964643111Z"
