apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-12-15T19:58:39.043189976Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5b51628233a87eb38746f1f49ac82a1a334316c2cb5f8582ef43129daa41ac55
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-15T19:58:39.046661095Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: e475760e9a36317bb16a3318040158ec77724196c5d27142a913923f3c9c8b01
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-15T19:58:39.048463245Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: fecd2763a25e06e831f3481bf853298b848deec0498d942a02e7fc833da9952b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-12-15T19:58:39.050109642Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 7c84ebee8eed2e973806d563ae12fa20a580613972416268d0745e7cc5ed97ab
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-12-15T19:58:39.052061693Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: b849922762c648d9edda55745a18d51e006e3284f3fe86ed2da1ddf3832c9dd4
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-15T19:58:39.053057854Z"
    description: helm chart for multicloud grc
    digest: 239d21e4355f29bca0591cbeb6c1cb69ed59f10f2c0a8dca86c356f4ab7e099a
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-12-15T19:58:39.053936848Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: be81ce774123de7399ecc4d7a110d7549a2d7db3efb4b84e858781c43b4b6187
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-12-15T19:58:39.054918949Z"
    description: Multi Cloud control plane ingress controller
    digest: 8bfb1564d02f278174d37b4a6c0db779f42156ffe5f810bc82b0c3ba26a89374
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-12-15T19:58:39.055852152Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 96578b6c81ba9c1b31d8a5fb0b51f625e30ff23c48941e5d365b2632ccf57510
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-12-15T19:58:39.056945657Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: ad7b003352c0d9fee97a032e826c27b24f8107d2a905641f6f92e0110322359b
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-15T19:58:39.057348358Z"
    description: helm chart for multicloud topology
    digest: 9812e98b19a1d2c2c52fe5d333e5ce424d884b5b0f7d22bd75e3ef3386cd93f5
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2020-12-15T19:58:39.042488304Z"
