apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-08-17T19:00:44.284912932Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 9ab02957984c3992937409d6b5ad9a6fd3056100c8732d6b5280e66aa4b3ab3b
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.0.tgz
    version: 2.1.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-08-17T19:00:44.288544621Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: be5f7daf918aa395231326d9211726dd41814886457b5ff5f0d98915af38facb
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.7.0.tgz
    version: 3.7.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-08-17T19:00:44.29002375Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 3d725ae64385c10cd195446c4eda3dcce45295060fec8ec85f4a9ebc294ac202
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.7.0.tgz
    version: 3.7.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-08-17T19:00:44.290874122Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 75827a03a538581126117a9d12c086cf27c23a567b1e7d9b1fc68593c8ba841d
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.7.0.tgz
    version: 3.7.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-08-17T19:00:44.292342818Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 553da92c4615e155b4db63980fe3a7dd9fd4bac132fae468824a4b10ef6f9939
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-17T19:00:44.293401468Z"
    description: helm chart for multicloud grc
    digest: 1260de6cf3fba5e8e5ba01000c02fa5b9384522d6d6ded4517d9a41a77b8d2cb
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.0.tgz
    version: 2.1.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-17T19:00:44.29523149Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 58239ae29fe503c1460ea21254180f541327150f01769a0b059c68e8e3ba8652
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.7.0.tgz
    version: 3.7.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-17T19:00:44.296712004Z"
    description: Multi Cloud control plane ingress controller
    digest: 47682c1c8575b139626ad249ff0ce215af0641f4adb700b9440f625bfe71ba2d
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-08-17T19:00:44.297568836Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 1b5825597f581e5bd6a83c566089179fdcce7deea20a757c6171032c26aa875d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-08-17T19:00:44.298617595Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 3530e9fb7c2db016e76dda565c70e872dd6cb9ef08d10082715e1eba26aec092
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.0.tgz
    version: 2.1.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-17T19:00:44.2990238Z"
    description: helm chart for multicloud topology
    digest: 74b75bdb090e129d7a8c015e486a8ea5bc953e79754c1d0462b4a70d0a406f73
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.0.tgz
    version: 2.1.0
generated: "2020-08-17T19:00:44.28336684Z"
