apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-09-18T08:30:20.333369544Z"
    description: Helm chart for Open Cluster Management application UI
    digest: b0134ceab73d0c58c7f5c61da6abaeb12d2256312d5f15c2fd3be12489f9ed3c
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.0.tgz
    version: 2.1.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-09-18T08:30:20.336765694Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 0897a422a1d966750bc7f122ecb5631f51ed64645dd7a358d5c8cc263689c6a1
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.7.0.tgz
    version: 3.7.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-09-18T08:30:20.338209241Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 59d570d76b15065e32066fccc0c25b54863651e52bc4a4e982e25f9c270a03a5
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.7.0.tgz
    version: 3.7.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-09-18T08:30:20.339359394Z"
    description: A helm chart for deploying the config map watcher component.
    digest: db4b9468b95edc65cec88e614d559a44803f235b4c3a818e0bd5a457a6d5fe5a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.7.0.tgz
    version: 3.7.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-09-18T08:30:20.341301063Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 05531a3e4cf7eb38f62fcc95fe4db9bea1f2ce08cca4dfe59dc62fc11a56f7cc
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-18T08:30:20.342376012Z"
    description: helm chart for multicloud grc
    digest: 67015867273ff223668423a0bce686a33abb50119da8c06202784453ef1ba6ce
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.0.tgz
    version: 2.1.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-09-18T08:30:20.343592885Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: b39ce8b4b30c28d804575939582a0d3869f5e4fd5eaf9e7c734b428b959c2ffb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.7.0.tgz
    version: 3.7.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-09-18T08:30:20.344549838Z"
    description: Multi Cloud control plane ingress controller
    digest: c5e27e36b9d5d6b2e2a3dbd92398cbdbd4322d1a5191da0e593fc304f767ebb9
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-09-18T08:30:20.345420591Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 04df581abb5672bca61f216a9af0e04cc0662d85439d1c1f94f116ea7ff2ebb8
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-09-18T08:30:20.346432063Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: a798cfa67b5a2eae991032807f87e93e674bcb620af27f1d57255ba230304a98
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.0.tgz
    version: 2.1.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-18T08:30:20.346814809Z"
    description: helm chart for multicloud topology
    digest: b03cd531fe69b1d0b42832afa33446a9c2499845340c459d9376e0004388f222
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.0.tgz
    version: 2.1.0
generated: "2020-09-18T08:30:20.331961747Z"
