apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-09-09T16:24:24.288568362Z"
    description: Helm chart for Open Cluster Management application UI
    digest: d27e1db35fffb2af4236e693940b458c3f7a72fbc55611eb949287051071b1ff
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.0.tgz
    version: 2.1.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-09-09T16:24:24.292040975Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 809e3e0064113117a8a2b8cd523cf0dc68ad4c75146118f017e899b447f2a0f0
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.7.0.tgz
    version: 3.7.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-09-09T16:24:24.293551888Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: c20b9b4b95394c2a92cd45d78674af34696195c4a29f53659f5e8fac9c464151
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.7.0.tgz
    version: 3.7.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-09-09T16:24:24.294407688Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 22bf15fc8468d2158273c338bc4c86a2c1cb88daead8f6c862200af51a8588a2
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.7.0.tgz
    version: 3.7.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-09-09T16:24:24.296523563Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 4ddd2d97236c0d6cab5acca6605daae6cadfafe6cca915190e6c9918a75996b2
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-09T16:24:24.297615858Z"
    description: helm chart for multicloud grc
    digest: c5033d7a535eaa0d7ae27f49e527181fb1ba38f2a8a37e1b0f5db2c9c9a284e4
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.0.tgz
    version: 2.1.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-09-09T16:24:24.299027618Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: f55268c698905ed97885976a8f73c58be47809e5cc3094991d8ac325ac86c8f2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.7.0.tgz
    version: 3.7.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-09-09T16:24:24.299997633Z"
    description: Multi Cloud control plane ingress controller
    digest: 0d31ac3826dd83424ad96d65500b81378ab61bf0e2e0e6acbf936833e989c387
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-09-09T16:24:24.300819173Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 91919ba8b5f20990330bb23874845e7994941be96699ea3faac302e406d24a44
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-09-09T16:24:24.301893474Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: b0aedc6395f53a02f01efceb2b45c3060b8de310a774e082d7fb0c32f749c40d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.0.tgz
    version: 2.1.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-09T16:24:24.302286583Z"
    description: helm chart for multicloud topology
    digest: 7b047b9677594fef6174d56616d8960e4b83300f9a701e905f76c5d1eebf6e8b
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.0.tgz
    version: 2.1.0
generated: "2020-09-09T16:24:24.287163227Z"
