apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-03T15:19:38.926720661Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 59357a9731579e7ae3589735f798f49b9fab82a61dfec50ddb667887630b74db
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-03T15:19:38.92784753Z"
    description: Service for issuing and managing certificates.
    digest: de9771388512af8991f9276f9e3ecb4fd04d9fb5f8f80898cd0e671f504016c7
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-03T15:19:38.931208859Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: cb6c5ecda58857c715e09951a6b4bdb10cb61f81799ca621d399aea4996d8ef9
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-03-03T15:19:38.932427647Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 0dc0bf0b32928772064dc5467f1ab4499bbbb5f99420ea33f1012a9786ecbb1f
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-03T15:19:38.933176693Z"
    description: Helm chart for Open Cluster Management Console
    digest: 9805c33cdf903e52d0b6c2d4bd1e0c53beb00ac962438e30e78c9e38d3aa18dd
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-03T15:19:38.933670394Z"
    description: helm chart for multicloud grc
    digest: 14feca63d1e6bf75db543d66ced8bd579aafd9751c741321205176b11b3a0472
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-03T15:19:38.934458106Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: d9cd2624c538db7fb66645146b047fbaf9362058f8edbe083c239266b17f0502
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-03T15:19:38.935340911Z"
    description: Multi Cloud control plane ingress controller
    digest: 725774ef0c8aa2b35812ee0c74b2ae1b369641b9e8be77a22b3de7c2cecbf62d
    keywords:
    - ingress
    - nginx
    - network
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-03T15:19:38.936227891Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 181c04aee397c4a6e79638b184de245035d2577d8f2585694de93dba0b20be03
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-03T15:19:38.937692524Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 01e942a2ddd1de93c8af9f796fc6cfe05cb7b7a0cc93932ac8bbdf874191c472
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-03T15:19:38.926043742Z"
