apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-13T01:41:45.05762758Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 9b6b674b18cea73e3aedaad39308d9527d65f648595265924af6f4422878c81c
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-13T01:41:45.058702913Z"
    description: Service for issuing and managing certificates.
    digest: 90d2841de46179b951c4e9540d36ef4ab814aa4014346ea6ed2017fdc0a6edfe
    keywords:
    - amd64
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-13T01:41:45.060115479Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 6e00f7db64f7ba7b53a47c6b7764a784a3cf7c5b4c1776cf947613999d947641
    home: https://github.com/open-cluster-management/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/open-cluster-management/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  cluster-lifecycle:
  - apiVersion: v1
    appVersion: "2.3"
    created: "2021-03-13T01:41:45.060970969Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: fc487ef3b309efcbad0ca1ae408bc8e8e1732927f07e1187986176c0d66c08e0
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: cluster-lifecycle
    urls:
    - http://multiclusterhub-repo:3000/charts/cluster-lifecycle-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.8.0
    created: "2021-03-13T01:41:45.061660602Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 1e75740cd1360656b2669cdb0514525026a7c6f0c90e067cefc66e41723c916d
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-13T01:41:45.062350339Z"
    description: Helm chart for Open Cluster Management Console
    digest: 85c179b48505f672e8f80b2575cfa84670e2b01213ee49fc1f9ce4043cec9469
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-13T01:41:45.062831016Z"
    description: helm chart for multicloud grc
    digest: 90b2f343c312e1825385f46ce8fb393af61840ffb3c7db5fc3ebd30fc6fe2e8a
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-13T01:41:45.063693158Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 3f5251da30fe72101232510376c6037e518f19b712095826683997eece4a3418
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-13T01:41:45.065120079Z"
    description: Multi Cloud control plane ingress controller
    digest: 137c279c8562cb469d9ac57f26385324b59ff8faaccc96d8831a1821d67566b4
    keywords:
    - ingress
    - nginx
    - network
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-13T01:41:45.066949272Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 0edfc593b39e24ad7ea3ba2136e85d69180c59708ac1b31190c014f6598ee5c4
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-13T01:41:45.069385964Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 1164c34110cab73f6eaf635ff50c5b1ca9196afbc5e325fa80408693fd901f7c
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-13T01:41:45.056959028Z"
