apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-12-01T17:18:50.427445494Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 9e34ddbfaee1968cdfff1a20e00d0da73c3f47c9714e5e55af3bcfdb9c746893
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-01T17:18:50.431511319Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 41837ee0fcf3c78bc4389b6fa140a9d64cbd9215b249a8a28589b2ce20513069
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-01T17:18:50.433131063Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 02510ccc9823c8d3347a11264a86ed79b953114d993169cae0354b9f2f38cd97
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-12-01T17:18:50.435103244Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 180ee517cb64d59563d2d7bb75f7cdca49a76b4eff0c0f2c39a6f696a14e383f
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-12-01T17:18:50.437244903Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: b5aca725a134a39d3406063afa4b30192a40fe4aaf8292d34b4c89a7449e0c36
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-01T17:18:50.438535521Z"
    description: helm chart for multicloud grc
    digest: aa227746b5f5c1d49efd79e896492eec0c8a0dd0e035453c6980a9ccf926a83b
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-12-01T17:18:50.439730721Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 71f73d47a31bc80ff20668fd639bdaf88d0ab2cc84bd579a86db48962b8d3c87
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-12-01T17:18:50.440943521Z"
    description: Multi Cloud control plane ingress controller
    digest: 116b4ff8d85204ef22a6e6539606fc67491f4d8a59d5fce7ac132cc76825dcb4
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-12-01T17:18:50.441873331Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: d5cddd2631a26736da0da722aa5879acdc04e668052846b1b2e406ef2503e5b9
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2020-12-01T17:18:50.442923577Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 0397f20e43f640ba9d921cd69d75e00fbb3abf59afb0f21a5a1f2d15a877971d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-01T17:18:50.443334163Z"
    description: helm chart for multicloud topology
    digest: 311ac5eb7c59a6728fa847bd20f024640c419080e11be0fa8f3f85b1a56715bf
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2020-12-01T17:18:50.426664938Z"
