apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-02T05:50:26.961720708Z"
    description: Helm chart for Open Cluster Management application UI
    digest: c9e9a7c3ef8897c3ca8f23564890e13485ef70ed9cdde9d96a6fca8c26248ef7
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-02T05:50:26.962811568Z"
    description: Service for issuing and managing certificates.
    digest: 814f3b40c46d7b3394bf48b887807a7376d21d1fbb858bf807800a49c6cba176
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-02T05:50:26.966352114Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: a62cd0ea0b18847f0da652c97137a2e405dfc192c2b18570cc0de2e29b59682b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-03-02T05:50:26.967006478Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 5d6cdd7bcf4f06cffb6e7a5916266754a6501585341e91c6eac1aeebd11757d8
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-02T05:50:26.967643477Z"
    description: Helm chart for Open Cluster Management Console
    digest: 4cd6e992b5cceba71cd358d9bbc68249b5e1b3ef0c8a01819c4b91d5616c3f3d
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-02T05:50:26.968087106Z"
    description: helm chart for multicloud grc
    digest: 10f44733e22ce4f51dba02b604658df1b4aec7f34fe5048e1024b308a5563090
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-02T05:50:26.968892207Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 861e8a1d44cf4557adbf43aab8779bbf05a246c26808e6fb2aa0f55d1ae64715
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-02T05:50:26.969859964Z"
    description: Multi Cloud control plane ingress controller
    digest: b717265dac8e1960bbde94380349510f70cac066663ac31d51aa5ceb0e72dafb
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-02T05:50:26.970780018Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: c1ac801c6799d507971fc9578589fc13b49a02475f875d3d894bde7ae42d01b8
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-02T05:50:26.972260172Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 73d5a9850c29a365fe116e557b7811b458dde23aa1a1cb9c30b970701e61c419
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-02T05:50:26.961133939Z"
