apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-23T21:27:26.258783272Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 4dc4d9cd9748624b7d2bb48e6ca5cb6e86edaea2d75c08ebf2853d7a553ed1cf
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-23T21:27:26.259903838Z"
    description: Service for issuing and managing certificates.
    digest: 52640a4ae6c4f0b4f9426c5cd65b7d05a0cb4206b026fe78bcfef710fb18eb9d
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-23T21:27:26.261319085Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 9d3b4b67f400745eba5c770a0ee910589f1e298be368c8db14d6a85df5a4b0e0
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-23T21:27:26.261996307Z"
    description: A helm chart for deploying the config map watcher component.
    digest: b16c8a96f2279a379885869e6a3d45239ead0c24849e09a5c735ea3da30e636b
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-23T21:27:26.262695456Z"
    description: Helm chart for Open Cluster Management Console
    digest: ebda2192a8ab65a6b6f3ee721cf70f09399c155003be23da175b812d7fdb54c2
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-23T21:27:26.26312976Z"
    description: helm chart for multicloud grc
    digest: e489f9a8a308549d7432bc94914b04100315fd3b48198752f1013825c16ba27b
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-23T21:27:26.263965135Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 966d4bddc777facde3916dcc29263f3a61530ade1bc9041304556f8dd4878639
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-23T21:27:26.265041749Z"
    description: Multi Cloud control plane ingress controller
    digest: 74985f8030b6c46b20b8ba3d2f838e2e455d637a2986456ff65a2ef302b49065
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-23T21:27:26.265957724Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: b1e64f7e824fe811ecc508fbcacad3d0821a21c9d805b865e7118cfe8b3ffcd7
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-23T21:27:26.267414064Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 90be5770df3a9482585e82e65f788eb974d8c7a628afdddcd321be8253aa9cf5
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-02-23T21:27:26.258020408Z"
