apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-04T02:54:32.926506908Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 97d6fb2265d82575ddea81e0ad4fa0f5801224c057aa4be654b60bfcc037364a
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-04T02:54:32.927667863Z"
    description: Service for issuing and managing certificates.
    digest: e1c60c5e550503a940e9f537b5e5de122ab9695daedcbd3171d27b9bccabcfce
    keywords:
    - amd64
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-04T02:54:32.929151415Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 2bdf56a5a22fa4ba71a713e4b7d7a0dc87c7e8dd24bb720e63fde7263b48971a
    home: https://github.com/open-cluster-management/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/open-cluster-management/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.8.0
    created: "2021-03-04T02:54:32.929838893Z"
    description: A helm chart for deploying the config map watcher component.
    digest: abb93e5feec626decc565aaa55a5d0f012ff1a4a26282a8e6ac8e8f0abc8e093
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-04T02:54:32.930483947Z"
    description: Helm chart for Open Cluster Management Console
    digest: 1d6ee0c56269629186a5ef561ff52dbf65c923c330856b3cb3a860584454a72a
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-04T02:54:32.930879324Z"
    description: helm chart for multicloud grc
    digest: 921df83e0184d96844e075740ecaad937af79b1ed464778bdb233ef6bcc1b753
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-04T02:54:32.931708269Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 6a6c8d5c03d9a188219165994705f884f574046df427a1b02479026d9c73af23
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-04T02:54:32.932658748Z"
    description: Multi Cloud control plane ingress controller
    digest: db72ab9d7edc9aec0f30a3a139aff3bf22633d294fe154614a2dac49e08b5585
    keywords:
    - ingress
    - nginx
    - network
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-04T02:54:32.933554491Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: c77649f73a17d705697b0439bb039b702e31759a9a525546952415d0a6018336
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-04T02:54:32.935554192Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: ce94d637cd9ac3fad666a68e839830b5656a4be325afb84d49f7120d785b983c
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-04T02:54:32.925843777Z"
