apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-08T19:32:35.612870694Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 14511444777553229d0feb4aead13670801cbe52daeef5bf4f4fa210b45c62c7
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-08T19:32:35.613946764Z"
    description: Service for issuing and managing certificates.
    digest: b0eb43b77d531c49af97364582aeffb98ac64ae738381e9b1046061ffd440a81
    keywords:
    - amd64
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.4
    created: "2021-03-08T19:32:35.617108174Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 5637b7d83eb7a9b7d04d9ce24db2b4915fc3a8a40d830267728d170395d2b023
    home: https://github.com/open-cluster-management/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/open-cluster-management/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.8.0
    created: "2021-03-08T19:32:35.618085672Z"
    description: A helm chart for deploying the config map watcher component.
    digest: f97a80da8be8f2b82b1e0af96f34f1d603a62a305a9f5432d10b7ff43810fc0d
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-08T19:32:35.618790709Z"
    description: Helm chart for Open Cluster Management Console
    digest: c7307302d7af0338ee2fa779202f98e2a310b65e9528bf4460437aac7db49cd1
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-08T19:32:35.619210859Z"
    description: helm chart for multicloud grc
    digest: bb05c239cfdb96c195f25b7a6ae1e540486fd0439482ce3c8a787b7420692c19
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-08T19:32:35.619990234Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 90bb1317b14603737dfb04521ab8f94428154d3bed7c20bf9bffb7fc78c54c39
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-08T19:32:35.620847095Z"
    description: Multi Cloud control plane ingress controller
    digest: 5b40ee84098ca94976a2788ff13726327d1ddb4f3b65bd46ec34e709a9a4fcb6
    keywords:
    - ingress
    - nginx
    - network
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-08T19:32:35.621632621Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 90be2cc3fe86159108ffb06d54bbb0445cc81fb75700c0da438af7d8f3a5a31f
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-08T19:32:35.623117566Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: af13e9e40c97f8086803b639623859f2d99e09d2a2f31bc3a1164f99ac13567a
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-03-08T19:32:35.612207686Z"
