apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-18T20:57:32.345788123Z"
    description: Helm chart for Open Cluster Management application UI
    digest: d2a02e7dca7a2a1aa556007b22ce963801400db7c06fbb728d6ee54109b82d10
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-18T20:57:32.346830118Z"
    description: Service for issuing and managing certificates.
    digest: 082fbb373d5a98e463e0b28e44c51d4d57e1e2e9791ed387ec88b2a8243fc439
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-18T20:57:32.348272238Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 77637ad3b6821580e30953742f9d5f3873e99ad5cf88d29c5585c16fad2ed8e9
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-18T20:57:32.349062077Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 28457187faca709c9aeffb973338eb8ac3748ebeb2b92dfc9abd55054df7a7cb
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-18T20:57:32.349767633Z"
    description: Helm chart for Open Cluster Management Console
    digest: a947a1f431c184b0d77539f822254d6ce1e701f99c1a503c1ef909bd0029a745
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-18T20:57:32.350226791Z"
    description: helm chart for multicloud grc
    digest: 7eb1efb719caf4f0ebfd81dd46b628e50ae751c77765d251459ff73c7ff54531
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-18T20:57:32.351496061Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 82918fea3a39b63618fedc6a39ac228498246caeab05242b84bcd91403184e78
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-18T20:57:32.353540333Z"
    description: Multi Cloud control plane ingress controller
    digest: 4c2acfe96fb0b9b4ae1214f6a89b3ed134d89703c7e46710b9033af2c094259e
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-18T20:57:32.355518721Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2fb3a95bab4f3aa229267e9f410d9d3ea495f56aa04363984ca4b43d1d721a50
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-18T20:57:32.35706474Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 971db2d7a31078e1ca3def0d5e94c32933405b84655672d719af8b3f3b93b763
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-02-18T20:57:32.345086971Z"
